### PR TITLE
fix for preview image distortion (aspect ratio)

### PR DESCRIPTION
**Pull request by sbandol**

### CODE REVIEW

**Comment by mmackh** [comment]
Sorry could you post a screenshot of what this does? I don't quite know which bug you have run into.

**Comment by sbandol** [comment]
of course, sorry for not doing that in the first place.

here is a screenshot with the current implementation
img_5335


here is after my modification.
img_5336


the problem consist in drawing the image onto context without considering the aspect ratio of the image.

To replicate the problem , simply modify top space constraint of the Camera View Controller to -100.

**Comment by gklka** [comment]
Oh, that fix looks great. Could you please pull this?

**Comment by mmackh** [comment]
Thanks!

**Pull request merged**
